### ISSUE TITLE
Gmail y Facebook login no funciona

### ISSUE THREAD

**Issue by MauChavez** [andrebts/login-basics#7]
Buenas noches,
Estuve tratando de correr la app pero no lo conseguí, agregue el Json faltante las Keys entre todo lo demás y hasta consigo los permisos pero no me da una respuesta satisfactoria la app para el login con Facebook ni con Gmail,  sabrán de alguna falla?

**Comment by andrebts** [comment]
Hola Edson, tienes que acessar
https://developers.google.com/mobile/add?platform=android&cntapi=signin&cnturl=https:%2F%2Fdevelopers.google.com%2Fidentity%2Fsign-in%2Fandroid%2Fsign-in%3Fconfigured%3Dtrue&cntlbl=Continue%20Adding%20Sign-In

para obter lo arquivo de Google-services.json e pone en la raíz del módulo en uso (app) para resolver. Si usted me puede enviar un error detallado será más fácil de ayudar a solucionar. Gracias.
